apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: miApp
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miApp
      env: staging
  template:
    metadata:
      labels:
        app: miApp
        env: staging
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
